# Use the official GCC image
FROM gcc:latest

# Create and set the working directory
WORKDIR /code

# Copy the code into the container
COPY . /code

# Default command to compile and run
CMD ["sh", "entrypoint.sh"]
